image: node:latest

stages:
  - install
  - build
  - test
  - publish

cache:
  paths:
    - build/
    - node_modules/

install deps:
  stage: install
  script:
    - npm ci
  artifacts:
    paths:
      - node_modules/

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - build/

test:
  stage: test
  script:
    - npm run test

## bumping is handled prior to commit, using husky
# bump-version:
#   stage: bump-version
#   script:
#     - npm version patch
#   artifacts:
#     paths:
#       - package.json
#       - package-lock.json

publish:
  stage: publish
  script:
    - cd ./
    - pkg_name=$(node -p -e "require('./package.json').name")
    - pkg_vers=$(node -p -e "require('./package.json').version")
    - echo "About to publish $pkg_name@$pkg_vers"
    - npm publish
  variables:
    NPM_TOKEN: $NPM_TOKEN
